services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Data/'
            # - '../src/DataFixtures/'
            # - '../src/Catalog.php/'
            
    App\Service\ImageConverter: ~
            
    App\State\UserPasswordHasherProcessor:
        arguments:
            $persistProcessor: '@api_platform.doctrine.orm.state.persist_processor'
    App\EventListener\JWTCreatedListener:
        tags:
            - {
                name: kernel.event_listener,
                event: lexik_jwt_authentication.on_jwt_created,
                method: onJWTCreated
            }
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']